name: Keepalive Workflow
on:
  schedule:
    # 每天 08:09 UTC 跑一次（可改成你喜欢的时间；尽量避开整点高峰）
    - cron: "9 8 * * *"
jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        # 默认在距离上次提交 ≥45 天时，用 API 方式制造一次“活动”，不会污染提交历史
        # 更多选项见该 Action 说明
