name: Keepalive Workflow

on:
  # 手动触发
  workflow_dispatch:

  # 定时触发：每天 08:09 UTC 跑一次
  schedule:
    - cron: "9 8 * * *"

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        # 默认在距离上次提交 ≥45 天时，用 API 方式制造一次“活动”，不会污染提交历史
